# Generated by Django 4.0.6 on 2022-08-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_customer_alter_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
