# Generated by Django 4.0.6 on 2022-08-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orderitem_remove_order_quantity_remove_product_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
