# Generated by Django 4.0.6 on 2022-09-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_order_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
