# Generated by Django 4.0.6 on 2022-08-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_image_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('piece', 'piece'), ('litre', 'litre')], default='kg', max_length=10),
        ),
    ]
