# Generated by Django 4.0.6 on 2022-08-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_product_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('available', 'available'), ('out of stock', 'out of stock')], default='available', max_length=20),
        ),
    ]
