# Generated by Django 4.0.6 on 2022-08-23 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_product_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Out of stock', 'Out od stock')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Liter', 'Liter'), ('Piece', 'Piece')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
